### PR TITLE
Fix: loss overlay no longer displays if player dies after win condition triggered.

### LINKED ISSUE #18: Don't allow losing a level after already winning
Currently if you successfully finish a level, and then die immediately after, you lose.

### PR DESCRIPTION
**Pull request by TheBeville**
Fixes #18

### CODE REVIEW

File: lib/game.dart [hunk 1]
```diff
@@ -98,7 +98,7 @@ class GameClass extends Forge2DGame
   }
 
   void _onLost() {
-    overlays.add('LostDialog');
+    overlays.isActive('WonDialog') ? null : overlays.add('LostDialog');
```
Comment (alexobviously) [inline lib/game.dart:101]: it's fine but I would probably do
`if(!overlays.isActive(...`

**Review by alexobviously — APPROVED** [review]

File: lib/game.dart (hunk 1 above)
Comment (TheBeville) [reply lib/game.dart]: Noted, have changed
